### PR TITLE
change field to bool

### PR DESCRIPTION
**Pull request by International**
Hi guys!
I tried using the lib, but I received this error: `cannot unmarshal bool into Go struct field Device.generated_nickname of type string` when calling `.Devices()`. I've made a fix on my fork.

### CODE REVIEW

**Comment by simonporter007** [comment]
Rats. Tests should have caught that but I was using the examples given in the api docs and they didn't use generated_nickname. Want to add a GeneratedNickname: line in the test file too?

**Comment by International** [comment]
Hi Simon, do you mean something like: `GeneratedNickname: true` in the `d` object?

**Comment by simonporter007** [comment]
Yeah, I think that should have been enough to catch it.

**Comment by International** [comment]
@simonporter007 added, thanks!

**Pull request merged**
